### ISSUE TITLE
Project reasoning

### ISSUE THREAD

**Issue by davidkhala** [newity/crawler#2]
- We have already a database behind fabric peer, thus we can see BadgeDB as a cache storage, is it?
- I guess this project is based on block replay support powered by ChannelEventHub. Is it?
- What will be project target user? What interests a developer to use this than to use fabric-sdk-go?

**Comment by vadimInshakov** [comment]
@davidkhala Hi David! Sorry for late answer. 

_We have already a database behind fabric peer, thus we can see BadgeDB as a cache storage, is it?_
BadgerDB used by Crawler as just a storage for parsed info. Depending on the implementation of the parser, the data in the Crawler's storage may differ more or less from the data in peer's LevelDB. By the way, at the moment there are storage implementations available not only for BadgerDB, but also for NATS and Google Pub/Sub.

_I guess this project is based on block replay support powered by ChannelEventHub. Is it?_
Yes. More precisely, the implementation of this interface in the go sdk is used: https://pkg.go.dev/github.com/hyperledger/fabric-sdk-go@v1.0.0/pkg/common/providers/fab#EventService

_What will be project target user? What interests a developer to use this than to use fabric-sdk-go?_
This project helps any developer who needs to collect data from the blockchain to get rid of the need to write boilerplate code. Crawler offers simple abstractions (and default implementations of each) to cover any need for collecting data from the blockchain. I tried to make the tool as simple as possible and will stick to this principle in the future.

**Comment by davidkhala** [comment]
@vadimInshakov Thanks for your excellent answer, would you mind adding these to project FAQ section?

**Comment by vadimInshakov** [comment]
@davidkhala I think this is a good idea.
